packaging_format = 2

id = "spip"
name = "SPIP"
description.en = "CMS with a focus on collaborative edition and multilingualism"
description.fr = "CMS conçu pour l'édition collaborative et le multilinguisme"

version = "4.4.2~ynh1"

maintainers = ["cyp"]

[upstream]
license = "GPL-3.0-or-later"
website = "http://www.spip.net/"
demo = "https://demo.spip.net/"
admindoc = "https://www.spip.net/en_rubrique209.html"
userdoc = "https://www.spip.net/en_rubrique57.html"
code = "https://git.spip.net/spip/spip"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/spip"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.users_status]
    ask.en = "Choose the status of YunoHost users"
    ask.fr = "Choisissez le status des utilisateurs de YunoHost"
    type = "string"
    choices = ["Administrator", "Editor", "Visitor"]
    default = "Editor"

[resources]
        [resources.sources.main]
        url = "https://files.spip.net/spip/archives/spip-v4.4.2.zip"
        sha256 = "d2ea428936f4e5a412355ff29256af6a215f3fcd6ab916128a136bdf799d5850"
        in_subdir = false


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server libsodium23 sqlite3 php8.2-sqlite3 php8.2-curl php8.2-xml php8.2-gd php8.2-mysqli php8.2-zip"


    [resources.database]
    type = "mysql"
