packaging_format = 2

id = "spip"
name = "SPIP"
description.en = "CMS with a focus on collaborative edition and multilingualism"
description.fr = "CMS conçu pour l'édition collaborative et le multilinguisme"

version = "4.4.8~ynh1"

maintainers = ["cyp"]

[upstream]
license = "GPL-3.0-or-later"
website = "http://www.spip.net/"
demo = "https://demo.spip.net/"
admindoc = "https://www.spip.net/en_rubrique209.html"
userdoc = "https://www.spip.net/en_rubrique57.html"
code = "https://git.spip.net/spip/spip"

[integration]
yunohost = ">= 12.1.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/spip"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.users_status]
    ask.en = "Choose the status of YunoHost users"
    ask.fr = "Choisissez le status des utilisateurs de YunoHost"
    type = "select"
    choices = ["Administrator", "Editor", "Visitor"]
    default = "Editor"

[resources]
        [resources.sources.main]
        url = "https://files.spip.net/spip/archives/spip-v4.4.8.zip"
        sha256 = "881944c89e354633604c2b324f55e550f50284e0dca50bd47a358bf9a2a67d7a"
        in_subdir = false


    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "mariadb-server",
        "libsodium23",
        "sqlite3",
        "php8.4-sqlite3",
        "php8.4-curl",
        "php8.4-xml",
        "php8.4-gd",
        "php8.4-mysqli",
        "php8.4-zip"
    ]

    [resources.database]
    type = "mysql"
